### ISSUE TITLE
Video app is not working on 6.1

### ISSUE THREAD

**Issue by mj-linux** [elementary/videos#295]
### What Happened?

Video App is not opening, after clicking the icon nothing happens.
OS is Elementary OS 6.1

### Steps to Reproduce

click on Video App icon either from Dash or App menu or a Video File.

### Expected Behavior

Video App should open.
but upon click it does not responds.

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

### Log Output

```shell
Terminal output : 
flatpak run io.elementary.videos
Gtk-Message: 10:30:15.160: Failed to load module "canberra-gtk-module"
Gtk-Message: 10:30:15.161: Failed to load module "canberra-gtk-module"

(io.elementary.videos:2): GLib-CRITICAL **: 10:30:15.376: g_strsplit: assertion 'string != NULL' failed
```

**Comment by michaelradu** [comment]
Having the same issue, I would also like to add that I tried installing extra media codecs like other people suggested but it still didn't fix it.

**Comment by danrabbit** [comment]
This should be fixed by https://github.com/elementary/videos/pull/293

**Comment by N3koSempai** [comment]
I think this problem is not solved.
On my system (OS: elementary OS 6.1 Jólnir x86_64 Kernel: 5.11.0-43-generic) I have the same problem
application videos in version 2.9.0

What is the problem?
Video App does not open, after clicking on the icon nothing happens.
in the terminal the command io.elementary.videos is not found (the application is installed).

Steps to Reproduce
click on Video App icon either from Dash or App menu or a Video File or by entering io.elementary.videos in the terminal.

How did I get the error traces?
run command io.elementary.files
then search for a video and open with videos (application)

output:
```bash
(io.elementary.videos:2): GLib-CRITICAL **: 17:47:47.053: g_strsplit: assertion 'string != NULL' failed
```

**Comment by Marukesu** [comment]
@N3koSempai do you have the `org.freedesktop.Platform.ffmpeg-full` installed? if so what version?

videos had an runtime update in the latest release and need the 22.08 version of it.

**Comment by N3koSempai** [comment]
> @N3koSempai do you have the `org.freedesktop.Platform.ffmpeg-full` installed? if so what version?
> 
> videos had an runtime update in the latest release and need the 22.08 version of it.

How can I check if it is installed and the version?

**Comment by Marukesu** [comment]
flatpak info org.freedesktop.Platform.ffmpeg-full
